apiVersion: apps/v1
kind: Deployment
metadata:
  name: ridecell
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ridecell
  template:
    metadata:
      labels:
        app: ridecell
    spec:
      containers:
        - name: ride-cell-container
          image: deva0077/ridecell:${{ github.sha }}
          ports:
            - containerPort: 3000

