apiVersion: v1
kind: Service
metadata:
  name: your-app-service
spec:
  selector:
    app: ridecell
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer # Change this according to your networking needs
